server:
  port: 8088

spring:
  application:
    name: dubbo-demo-provider

dubbo:
  scan:
    base-packages: com.zachary.dubbo.demo.provider
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qos-enable: true
    qos-port: 22222
    qos-accept-foreign-ip: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost