spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3312/zzz?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialization-mode: always

  shardingsphere:
    props:
      sql:
        show:
          true
    datasource:
      names: zdb0, zdb1
      zdb0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3311/zzz?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        initialization-mode: always
      zdb1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3312/zzz?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        initialization-mode: always
    sharding:
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: zdb$->{user_id % 2}
      tables:
        order:
          actual-data-nodes: zdb$->{0..1}.order_$->{0..15}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_$->{id % 16}
#          key-generator-column-name: id
#          key-generator-class-name: org.apache.shardingsphere.core.strategy.keygen.SnowflakeShardingKeyGenerator
order:
  table:
    num: 16

