
spring:
  kafka:
    bootstrap-servers: http://localhost:9001,http://localhost:9002,http://localhost:9003
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ideal-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 20000
server:
  port: 9999